org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true

# Versions can be found at https://parchmentmc.org/docs/getting-started
neoForge.parchment.minecraftVersion=1.21.5
neoForge.parchment.mappingsVersion=2025.04.19

modid=obtrophies
mod_name=OpenBlocksTrophies

minecraft_version=1.21.5
neo_version=21.5.73-beta
mod_version=5.1

jei_version=19.5.0.40
rei_version=16.0.729
emi_version=1.1.10
