org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Versions can be found at https://parchmentmc.org/docs/getting-started
neoForge.parchment.minecraftVersion=1.21.11
neoForge.parchment.mappingsVersion=2025.12.20

modid=obtrophies
mod_name=OpenBlocksTrophies

minecraft_version=26.1.2
neo_version=26.1.2.76
mod_version=5.1

jei_version=29.6.2.38
rei_version=16.0.729
emi_version=1.1.10
