modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/GizmoTheMoonPig/OpenBlocksTrophies/issues"

[[mods]]
modId="obtrophies"
version="${file.jarVersion}"
displayName="OpenBlocks Trophies"
displayURL="https://www.curseforge.com/minecraft/mc-mods/entity-trophies"
logoFile="trophy.png"
credits="Original Trophies made by the OpenMods team"
authors="GizmoTheMoonPig"
description='''
Brings back the trophies from Openblocks.
'''

[[dependencies.obtrophies]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.obtrophies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
