name: Compatibility
description: Create a ticket to suggest mod compatibility
title: "[Compat] "
labels: [mod-compat]
body:
  - type: input
    attributes:
      label: Mod Suggestion
      description: The mod you would like to see compat with. I would recommend a Curseforge link, but you can just put the mod name here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why Should It Be in the Mod?
      description: Describe why you think this mod should be included.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Please Read and Confirm the Following
      options:
        - label: I have confirmed this suggestion is unique and has not been suggested already.
          required: true
        - label: I have confirmed this mod does not make use of Geckolib. Geckolib models dont stay static when displaying as trophies, and because of this I have decided not to add them until I find a workaround or Geckolib fixes this problem.
        required: true
