name: Mod Compatibility
description: Create a ticket to suggest mod compatibility
title: "[Compat] "
labels: [mod-compat]
body:
  - type: input
    attributes:
      label: Mod Suggestion
      description: The mod you would like to see compatibility with. I would recommend a Curseforge link, but you can just put the mod name here.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Please Read and Confirm the Following
      options:
        - label: I have confirmed this mod has not been suggested and/or added already.
          required: true